# Generated by Django 4.2.7 on 2023-11-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BreedName', models.CharField(blank=True, max_length=10000, null=True)),
                ('PetName', models.CharField(blank=True, max_length=10000, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('No_of_pets', models.IntegerField(blank=True, null=True)),
                ('No_of_pets_sold', models.IntegerField(blank=True, null=True)),
                ('Total_price', models.IntegerField(blank=True, editable=False)),
            ],
        ),
    ]
